# dist: trusty # KVM Setup

# For now only "linux" as it looks like docker
# is not available on "osx"
os:
  - linux

language: go

go:
  - 1.10.2

env:
  - TEST_VERBOSE=1

script:
  - make -k test

# For docker containers

sudo: required

services:
  - docker
